## 仪表板(Dashboard)详解

这一部分是关于Dashboard的内容。在这一部分中你不需要写任何代码。这一部分只是解释Dashboard的一些工作原理：

1. 如何配置Vert.x Web以便访问静态资源
2. 如何配置SockJS - Event Bus 通信通道(bridge)
3. 如何实现基于其它REST服务的REST端点（代理模式）
4. 如何在浏览器端使用Event Bus服务

Dashboard部分是一个单独的Verticle (`io.vertx.workshop.dashboard.DashboardVerticle`)。

### Vert.x Web与静态文件

正如我们之前所提到的那样，Vert.x Web是一个用于构建Web应用的Vert.x组件。整个架构的核心是 `Router` 对象（路由）。
你可以创建并配置**路由**。对每一个路由，你都需要配置其 _HTTP Method_ 与 _URL路径_ ，并与对应的 `Handler` 相结合。
`router` 对象可以通过下面的代码进行创建：

[source, java]
----
Router router = Router.router(vertx);
----

Vert.x Web提供了一系列的 `Handler` 用于处理各种请求，比如访问静态资源：

[source, java]
----
// 静态内容
router.route("/*").handler(StaticHandler.create());
----


当路由配置完毕后，你需要创建一个HTTP服务端并使用路由来处理HTTP请求：

[source, java]
----
vertx.createHttpServer()
    .requestHandler(router::accept)
    .listen(8080);
----

### SockJS - Event Bus 通信通道

**SockJS**是一个提供类似于WebSocket对象的JavaScript库。SockJS提供了一组一致的、跨浏览器的JavaScript API，这组API可以用于创建浏览器和服务端之间的，低延时、全双工、跨域的通信通道(communication channel)。
在底层，SockJS首先会尝试使用原生的WebSocket，如果失败了则会尝试使用各种不同的浏览器相关的传输协议，并且会将其通过类似于WebSocket的抽象结果呈现出来。
SockJS客户端需要一个对应的处理通信的服务器，而且你可以想象到，Vert.x帮你实现了！

有了SockJS - Event Bus通信通道，来自Event Bus的事件可以被发送到浏览器端，而且我们也可以用JavaScript代码向Event Bus发送消息。

你需要添加以下代码开启SockJS - Event Bus Bridge功能：

[source, java]
----
SockJSHandler sockJSHandler = SockJSHandler.create(vertx);                      // <1>
BridgeOptions options = new BridgeOptions();
options
    .addOutboundPermitted(new PermittedOptions().setAddress("market"))         // <2>
    .addOutboundPermitted(new PermittedOptions().setAddress("portfolio"))
    .addOutboundPermitted(new PermittedOptions().setAddress("service.portfolio"))
    .addInboundPermitted(new PermittedOptions().setAddress("service.portfolio"));

sockJSHandler.bridge(options);                                                 // <3>
router.route("/eventbus/*").handler(sockJSHandler);                            // <4>
----

在 (1) 中，我们创建了 `SockJSHandler`。我们需要对其进行配置，因为默认情况下，为了安全起见不允许传输任何数据，因此我们需要指定能够传输数据对应的地址 (2)。
`Outbound` 地址代表从Event Bus向浏览器端传输，而 `Inbound` 地址代表从浏览器端向Event Bus传输。最后在 (3) 和 (4) 中，我们对 `Handler` 进行了配置，并且通过 `router` 配置了路由。
`/eventbus/*` 这个路径会被SockJS 客户端（浏览器端）用于识别连接以及发送和接受消息。

这并不是Event Bus唯一的通信通道，Vert.x还为原生系统实现了TCP Event Bus Bridge。并且，SockJS通道也可用于Node.js。

### 委托REST调用

我们常常需要基于另一个REST API来实现我们的REST API，这种模式在传统的架构中性能代价很大，因为它会一直阻塞调用线程，直到完成另一个REST API的调用过程。
而在Vert.x的异步、非阻塞模型下，一切问题都迎刃而解。

比如在Dashboard中，我们想要获取最近的操作列表。而操作列表由审计服务提供，因此在Dashboard中我们设有如下的路由：

[source, java]
----
router.get("/operations").handler(this::lastOperations);
----

对应的 `Handler`：

[source, java]
----
private void lastOperations(RoutingContext context) {
    HttpEndpoint.get(vertx, discovery, new JsonObject().put("name", "AUDIT"), client -> {
        if (client.failed() || client.result() == null) {
            context.response()
                .putHeader("content-type", "application/json")
                .setStatusCode(200)
                .end(new JsonObject().put("message", "No audit service").encode());
        } else {
            client.result().get("/", response -> {
              response
                  .exceptionHandler(context::fail)
                  .bodyHandler(buffer -> {
                    context.response()
                        .putHeader("content-type", "application/json")
                        .setStatusCode(200)
                        .end(buffer);
                    client.result().close();
                  });
            })
                .exceptionHandler(context::fail)
                .end();
        }
    });
}
----

### 在浏览器端使用Event Bus服务

正如我们之前所说的，SockJS与Event Bus之间存在通信通道，可以让浏览器发送和接收消息。因为Event Bus服务通过Event Bus消息进行通信，这使得在浏览器端实现一个客户端成为可能。Vert.x自动为你生成此客户端。

所以，如果你浏览 `index.html` 的源码，你会看到：

[source, html]
----
<script src="libs/portfolio_service-proxy.js"></script>
----

下面我们就可以使用服务了：

[source, javascript]
----
var service = new PortfolioService(eventbus, "service.portfolio");
service.getPortfolio(function (err, res) {
   // ....
}
----

是的，你可以直接在你的浏览器里调用相应的服务了。



