## 环境准备

现在是你开始实践的时候了！在我们开始之前，我们要先配好环境。

### 硬件要求

* 操作系统：Mac OS X (10.8+), Windows 7+, Ubuntu 12+, CentOS 7+, Fedora 22+
* 内存：最少4 GB，推荐8 GB以上

### Docker

#### Docker工具箱/安装包

Docker可以原生运行于Linux下。因为Docker底层使用了Linux内核的某些特性，因此目前你还不能在Windows或OS X下直接运行Docker
（Docker团队正致力于其原生运行）。所以，你需要使用 `docker-machine` 来创建一个虚拟机(VM)。这个虚拟机里运行着Linux系统，可以通过它
来运行Docker。利用 https://www.docker.com/docker-toolbox[Docker Toolbox]，你可以很方便地安装Docker环境。

你可以按照以下指示来安装Docker：

* https://github.com/docker/toolbox/releases/download/v1.10.3/DockerToolbox-1.10.3.pkg[Docker Tool Box 1.10.3 for Mac]
* https://github.com/docker/toolbox/releases/download/v1.10.3/DockerToolbox-1.10.3.exe[Docker Toolbox 1.10.3 for
Windows]
* http://docs.docker.com/engine/installation/ubuntulinux/[Docker on Ubuntu]
* http://docs.docker.com/engine/installation/centos/[Docker on Centos]
* http://docs.docker.com/engine/installation/fedora/[Docker on Fedora]

完整的操作系统列表可以在 http://docs.docker.com/engine/installation/[Install Docker Engine] 找到。

#### 镜像

为了避免在实现应用的时候等待下载Docker镜像，你需要提前下载好镜像：

[source]
docker pull library/java

#### 创建Docker主机映射

如果你在使用Docker Machine，为了可以更容易地启动/结束容器，你需要在hosts文件里加一条记录。

首先查询你的电脑目前的IP地址：

[source]
----
docker-machine ip default
----

IMPORTANT: 将 `default` 替换为你的Docker Machine名。

然后编辑 `/etc/hosts` (Mac OS X) 或 `C:\Windows\System32\drivers\etc\hosts` (Windows)文件，添加一行：

[source, text]
----
<IP ADDRESS>  dockerhost
----

对Linux用户来说， `dockerhost` 与 `localhost` 相同（因为Docker可以原生运行）。你需要将上面对应的 `dockerhost` 替换成 `localhost`。

### JDK

你需要在电脑上安装JDK 8。可以从官网下载并安装：

* http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8]

### Maven

* 从 https://maven.apache.org/download.cgi 下载 Apache Maven。
* 解压压缩包，并且设置环境变量 `PATH` 。

### IDE

我们推荐你用IDE进行编程，比如Eclipse、IntelliJ IDEA或者Netbeans。

#### 没有安装IDE ?

如果你电脑里没有安装IDE，你可以根据下面的指示安装Eclipse：

1. 首先进入 https://www.eclipse.org/downloads/[下载页] 。
2. 在 _Eclipse Package_ 列表里选择 _Eclipse IDE for Java Developers_ 这一项。它会指引你下载。
3. 下载完以后，解压压缩包。
4. 在解压好的文件夹中，你可以找到 `Eclipse` 对应的可执行文件。
5. Eclipse指引你创建一个工作空间(workspace)。
6. 启动Eclipse以后，点击 _Workbench_ 箭头 (右上角)。

