## Vert.x

让我们首先在几行之内解释一下Vert.x是什么。正如之前的章节所说的，Vert.x是 _“一个在JVM上构建
响应式应用的一个工具集(toolkit)”_ 。

这里面第一个重要的词是 **工具集** 。所以，Vert.x不是一个应用服务器，也不是一个容器或一个框架。
它也并非JavaScript库。Vert.x是一个 `jar` 包，所以一个Vert.x应用就是一个使用 `jar` 包的应用。
Vert.x没有自己定义一个打包模型，每一个Vert.x _组件_ 都是普通的 `jar` 文件。
这如何影响你的应用呢？我们假设你正在使用某种构建工具以给你的应用添加 `vertx-core` 依赖，比如Maven或Gradle。
如果希望使用其它的Vert.x组件，只要把它作为一个依赖添加到构建文件里即可，这非常简单。我们通过一个包含
`public static void main(String[] args)` 函数的类启动程序。我们不需要安装特定的IDE和各种插件。

然后，要想利用Vert.x提供的各种优美功能，你只需要在代码里运用它。耐心一点，我们将在下面介绍它的使用。

另一个重要的词是 **响应式(reactive)** 。Vert.x就是为构建响应式应用（系统）而设计的。响应式系统这个概念在
http://reactivemanifesto.org[Reactive Manifesto] 中有详细的定义。尽管那篇文章读起来用时不长，
我们在这里总结4个重点：

* 响应式的(Responsive)：一个响应式系统需要在 _合理_ 的时间内处理请求（何谓合理？我把它交给您来定义）。
* 弹性的(Resilient)：一个响应式系统必须在遇到 _异常_ （崩溃，超时， `500` 错误等等。。）的时候保持响应的能力，
所以它必须要为 _异常处理_ 而设计。
* 可伸缩的(Elastic)：一个响应式系统必须在不同的负载情况下都要保持响应能力，所以它必须能伸能缩，
并且可以利用最少的资源来处理负载。
* 消息驱动：一个响应式系统的各个组件之间通过 **异步消息传递** 来进行交互。

其中最后一条展示了Vert.x的本质 - 它是事件驱动的，也是非阻塞的。事件在 _Event Loop_ 线程里进行传递， **你在任何时候都不能去阻塞它** 。
我们来解释一下为什么。与传统的“企业级”系统不同，Vert.x使用非常少的线程。其中的一些线程叫做 _Event Loop_ 线程，它们用来快速处理
`Handler` 中的事件。如果你把这个线程给阻塞了，那么事件传递的过程就将会被阻塞，事件就不能被传递。
这种执行模型对你的代码风格有着深远的影响。我们要抛弃 _传统_ 的阻塞风格的代码，然后写出异步的 footnote:[异步: 调用者不需要一直等待返回结果，
而是传递一个 _回调函数_ 。当得到结果时，回调函数会被调用]、非阻塞的 footnote:[非阻塞: 代码不能阻塞执行线程 -
所以必须避免阻塞IO，也就是需要长时间处理过程的方法]代码。

之前，你可能在写如下的代码：

[source, java]
----
URL site = new URL("http://vertx.io/");
BufferedReader in = new BufferedReader(new InputStreamReader(site.openStream()));

String inputLine;
while ((inputLine = in.readLine()) != null) {
  System.out.println(inputLine);
}
in.close();
----

那只是往事了。有了Vert.x后，你可以这么写：

[source, java]
-----
vertx.createHttpClient().getNow(80, "vertx.io", "", response -> {
  response.bodyHandler(System.out::println);
});
-----

这两段代码的主要不同之处：

* 第一段代码是同步、阻塞的：每条指令 _按顺序_ 执行，但有的指令可能会
会长时间阻塞执行线程（因为网站访问可能会很慢，或者是其它原因）。
* 用Vert.x写的代码是异步、非阻塞的：Event Loop线程在与HTTP服务端建立连接后就会保持空闲以便处理其它事件。
当收到响应时，**同一个**Event Loop线程会调用回调函数。许多Vert.x组件都是单线程的（仅通过一个线程访问），
所以不存在并发的各种问题。

另一个Vert.x描述里重要的一点就是“ _在JVM上_ ”。Vert.x应用都运行于JVM（Java 8+）上，但这并不意味着
开发者必须要用Java语言去编写Vert.x应用。Vert.x应用当然可以用Java编写，但也可以用Groovy、Ceylon、Ruby、JavaScript等等
的语言编写，甚至混合起来写也可以！这种多语言的特性可以让您使用最恰当的编程语言来完成您的任务。

Vert.x支持实现分布式应用，既可以通过内建的TCP和HTTP服务端/客户端实现，也可以通过Vert.x的Event Bus（事件总线）来实现。
Event Bus是一个轻量级的发送和接受消息的结构，有了Event Bus，你可以向某些 `地址` 发送消息。它支持三种分布式机制：

1. _点对点_ ：消息被发送到监听某个地址的某一个 _消费者_ 处
2. _发布/订阅_ ：消息可以被监听某个地址的所有 _消费者_ 接收
3. _请求/回复_ ：消息被发送至某个消费者处，并且可以向发送源发送另一条消息来**回应**

好啦，我们最后用一分钟的时间来总结一下你为什么要使用Vert.x。Vert.x非常灵活 —— 无论是简单的网络功能，
复杂的现代Web应用，HTTP/REST 微服务，高并发事件处理，还是一个后端事件处理应用，Vert.x都可以胜任。它速度快，并且不限制你的开发结构。
最后一点，Vert.x不仅仅自身是响应式的，它还可以将你的应用变为响应式风格的。用几个词概括一下：**响应式、伸缩性、弹性、异步**！

