## Let's start !

### Getting the code

[source]
----
git clone https://github.com/cescoffier/vertx-microservices-workshop
----

You can import the code in your IDE as a Maven project. Refer to your IDE documentation to know how to import Maven
projects.

TIP: The complete solution is given in the `solution` directory.

### Build

The build is managed using Apache Maven. Compile everything using:

[source]
----
cd vertx-microservices-workshop
mvn clean install
----

### The discovery infrastructure

It's time to start. If you remember the microservice section, we need some discovery mechanism. Fortunately, Vert.x
offers a discovery service. To let every component discovery the service, it needs to store the service _record_ in a
 location that every one can request. This is obviously configurable in Vert.x, but let's use the default
 implementation.

By default, Vert.x discovery service is going to use a distributed map accessible by all the members of the cluster.
So, when you start your vert.x application and enable the cluster mode, it joins a cluster. This cluster lets:

* node to come and go, and so manage member discovery
* share data such as distributed map, lock, counter...
* implement the distributed event bus

In our context, nothing is required to configure it. Our docker images already start the Vert.x applications in
cluster mode.

