## Let's start !

### Getting the code

[source]
----
git clone https://github.com/cescoffier/vertx-microservices-workshop
----

You can import the code in your IDE as a Maven project. Refer to your IDE documentation to know how to import Maven projects.

For Eclipse:

1. Click on `File - Import ... - Maven - Existing Maven Projects`
2. Select the location where you cloned the sources
3. Click _Finish_ and wait...

You are going to see a couple of compilation errors. This is because Eclipse does not mark the `src/main/generated`
directories as _source root_ by default. Right-click on `portfolio-service/src/main/generated` and select _Build Path
-> Use as Source Folder_.

TIP: A complete solution is given in the `solution` directory.

### Build

The build is managed using Apache Maven. Compile everything using:

[source]
----
cd vertx-microservices-workshop
mvn clean install
----

### Clustering and Discovery infrastructure

It's about time to start. If you remember the microservice section, we need some discovery mechanism. Fortunately,
Vert.x offers a discovery service. To let every component discover the services, it needs to store the service
_record_ in a location that every one can access.

By default, Vert.x discovery service is going to use a distributed map accessible by all the members of the cluster.
So, when you start your Vert.x application and enable the cluster mode, it joins a cluster. This cluster lets nodes:

* to come and go, and so manage member discovery
* to share data such as distributed maps, locks, counters...
* to access the event bus

In our context, nothing is required to configure it. Our docker images already start the Vert.x applications in
cluster mode.

In this lab, the cluster is built on top of Hazelcast and the member discovery uses _multicast_.

