## Vert.x

We will attempt to explain Vert.x in just a few lines. Remember that we said in the previous section that Vert.x is _"a toolkit for building
reactive applications on the JVM"_.

There are a three important points in this description: **toolkit**, **reactive** and _"on the JVM"_.

Firstly, Vert.x is a **toolkit**. Meaning, Vert.x is not an application server, a container nor a framework.
It's not a JavaScript library either. Vert.x is a plain old `jar` file, so a Vert.x application is an application that uses this `jar`
 file. Vert.x does not define a packaging model, all Vert.x _components_ are plain _boring_
 `jar` files. How does this impact you and your application? Let's imagine you are using a build tool such as
 Maven or Gradle, to make your application a Vert.x application just add the `vertx-core` dependency. Wanna use another
 Vert.x components, just add it as a dependency. It's simple, burden-less. Starting the application is a simple class
 with the `public static void main(String[] args)` entry point. No specific IDE or plugin to install to start using Vert.x.

Therefore, to use the awesomeness provided by Vert.x, you just need to use it in your code, but be patient, this will be
covered later.

Secondly, Vert.x is **reactive**. It is specifically made to build reactive
applications, or more appropriately, **systems**. Reactive systems footnote:[Reactive systems and reactive programming are two
different _things_. Reactive programming is a development model observing and manipulating data streams, while
reactive systems are systems that reacts to requests, failures, load peaks and interacts using async messages.] has
been defined in the  http://reactivemanifesto.org[Reactive Manifesto]. Although, it's not long document to read, we will further reduce it to these 4 bullet points:

* Responsive: a reactive system needs to handle requests in a _reasonable_ time (I let you define _reasonable_).
* Resilient: a reactive system must stay responsive in the face of _failures_ (crash, timeout, `500` errors...), so
it must be _designed for failures_ and deal with them appropriately.
* Elastic: a reactive system must stay responsive under various loads. As a consequence, it must scale up and down, and
be able to handle the load with minimal resources.
* Message driven: components from a reactive system interacts using **asynchronous message-passing**.

Also, Vert.x is event-driven and also non-blocking. Events are delivered in an
_event loop_ that **must never be blocked**. Let's explain why. Unlike traditional, let's say "enterprise", systems,
Vert.x uses a very small number of threads. Some of these threads are _event loops_, they are responsible for
dispatching the events in `Handlers`. If you block this thread, the events won't be delivered anymore. This
execution model impacts how you write your code, instead of the _traditional_ model of blocking code, your code is
going to be asynchronous footnote:[Asynchronous: the caller does not wait for a returned response, but pass
 a _callback_ which is executed when the result has been computed] and non-blocking footnote:[Non-blocking: the code
  must not block the executing thread - so it must avoid blocking IO, long processing time etc.].

As an example, if we wanted to retrieve a resoure from a URL, we would do something like this:

[source, java]
----
URL site = new URL("http://vertx.io/");
BufferedReader in = new BufferedReader(new InputStreamReader(site.openStream()));

String inputLine;
while ((inputLine = in.readLine()) != null) {
  System.out.println(inputLine);
}
in.close();
----

But with Vert.x we are more likely to do:

[source, java]
-----
vertx.createHttpClient().getNow(80, "vertx.io", "", response -> {
  response.bodyHandler(System.out::println);
});
-----

The main differences between these 2 codes are:

* the first one is synchronous and potentially blocking : the instructions are executed in _order_, and may block the thread
for a long time (because the web site may be slow or whatever).
* the Vert.x one is asynchronous and non-blocking: the thread (event loop) is released while the connection with the
HTTP server is established and so can do something else. When the response has been received, the **same** event loop
 calls the _callback_. Most of the Vert.x components are single-threaded (accessed only by a single thread), so no
 concurrency burden anymore. By the way, with Vert.x, even the DNS resolution is asynchronous and non-blocking (while
 Java DNS resolution is blocking).

Finally, Vert.x applications runs _"on the JVM"_
the Java Virtual Machine (8+). This means Vert.x
applications can be developed using any language that runs on the JVM. Including Java(of course), Groovy, Ceylon, Ruby, JavaScript, Kotlin and Scala.
We can even mix and match any combination of all these languages. The polyglot nature of Vert.x application allows you use the most appropriate language for the task.

Vert.x lets you implement distributed applications, either by using the built-in TCP and HTTP server and client, but
also using the Vert.x event bus, a lightweight mechanism to send and receive messages. With the event bus, you send
messages to `addresses`. It supports three modes of distributions:

1. _point to point_: the message is sent to a single _consumer_ listening on the address
2. _publish / subscribe_: the message is received by all the _consumers_ listening on the address
3. _request / reply_: the message is sent to a single _consumer_ and let it _reply_ to the message by sending another
_message_ to the initial sender

Wao!, that's a lot of information to process... However, you might still want to ask: **What kind of applications can I use Vert.x for?** We say, Vert.x is
incredibly flexible - whether it's simple network utilities, sophisticated modern web applications, HTTP/REST
microservices, high volume event processing or a full blown backend message-bus application, Vert.x is a great fit.
It's fast, and does not constraint you. Last but not least, Vert.x provides appropriate tools to build reactive systems; systems that are: _responsive, elastic, resilient and asynchronous_!


